# Hand labels for rows 1-200 (human judgment; writer only merges).
# Format: id -> (label, notes_reason)
ANNOTATIONS_1_200 = {
"en_otp_web_3768": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务结果，非骗术"),
"en_otp_web_57199": ("TRANSACTION", "RailWire上网验证码，服务接入认证，正文无假冒/索要转账"),
"en_otp_web_17423": ("TRANSACTION", "银行卡交易OTP（Swiggy消费确认），属事务认证"),
"en_otp_web_9301": ("TRANSACTION", "推荐信息核验OTP，应用内认证，无诈骗话术"),
"en_otp_web_33194": ("TRANSACTION", "配送签收OTP+物流时段告知，快递取件码属事务"),
"en_otp_web_57661": ("TRANSACTION", "Paytm付款卡OTP，并警示勿向他人泄露，属交易认证"),
"en_otp_web_58509": ("TRANSACTION", "Pariksha平台OTP，纯验证码认证"),
"en_otp_web_16488": ("TRANSACTION", "ECI用户管理OTP，账户操作认证"),
"en_otp_web_16399": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4550": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1386": ("TRANSACTION", "银行无法确认大额转账的账户业务告知，含官方争议电话"),
"en_otp_web_19476": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16784": ("TRANSACTION", "UIDAI Aadhaar OTP，官方KYC认证+官方域名指引"),
"en_otp_web_17883": ("TRANSACTION", "BhaiFi接入OTP，纯服务认证，无骗术"),
"en_otp_web_4796": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58383": ("TRANSACTION", "Ecom Express预付件签收OTP，物流业务"),
"en_otp_web_3374": ("TRANSACTION", "MakeMyTrip用户验证OTP，登录/核验认证"),
"en_otp_web_9788": ("TRANSACTION", "Akshayakalpa App验证OTP，完成核验用"),
"en_otp_web_16963": ("TRANSACTION", "Ipsos调查平台验证码，账号认证"),
"en_otp_web_16454": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_327": ("TRANSACTION", "银行卡消费成功通知+可用额度，典型账户变动告知"),
"en_otp_web_57276": ("TRANSACTION", "Steam确认码，平台认证"),
"en_otp_web_12289": ("TRANSACTION", "Porter妥投确认码，物流签收事务"),
"en_otp_web_8291": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_36055": ("TRANSACTION", "Supr Delivery配送签收OTP，物流事务"),
"en_otp_web_20010": ("TRANSACTION", "Porter妥投确认码，物流签收事务"),
"en_otp_web_10207": ("TRANSACTION", "Apple ID验证码，官方账户认证"),
"en_otp_web_17476": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1646": ("TRANSACTION", "YES BANK外币卡消费/钱包扣款余额告知"),
"en_otp_web_21344": ("TRANSACTION", "ICICI UPI注册已开始的安全提醒，账户业务告知"),
"en_otp_web_8307": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_31611": ("TRANSACTION", "Naukri平台反诈服务告知（勿为职位付费/泄密），非推销非骗局"),
"en_otp_web_9720": ("TRANSACTION", "Ecom Express到件+签收码，物流事务"),
"en_otp_web_16749": ("TRANSACTION", "Aadhaar OTP+官方1947锁卡指引，KYC认证"),
"en_otp_web_57231": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_17447": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57201": ("TRANSACTION", "Google验证码，平台认证；源phishing弱标签不可信"),
"en_otp_web_58761": ("TRANSACTION", "网约车行程信息+上车OTP，出行服务事务"),
"en_otp_web_3629": ("TRANSACTION", "BookMyForex验证OTP，应用认证"),
"en_otp_web_58759": ("TRANSACTION", "网约车上车OTP+接驳指引，出行服务事务"),
"en_otp_web_8221": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_49856": ("TRANSACTION", "MyGP PIN验证码，支付/账户认证"),
"en_otp_web_58749": ("TRANSACTION", "KrazyBee注册OTP，应用注册认证"),
"en_otp_web_4553": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_7781": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57916": ("TRANSACTION", "邮箱变更审批OTP，账户安全认证"),
"en_otp_web_8266": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58821": ("TRANSACTION", "SBI借记卡网购OTP（Amazon），交易认证"),
"en_otp_web_3288": ("TRANSACTION", "Acko验证OTP，保险App认证"),
"en_otp_web_29677": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_17881": ("TRANSACTION", "BhaiFi接入OTP，纯服务认证"),
"en_otp_web_55313": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_1597": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_4265": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1892": ("TRANSACTION", "Amazon Fresh取件/配送状态+官方跟踪链，物流事务"),
"en_otp_web_29670": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_4396": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29773": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_3129": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16964": ("TRANSACTION", "LinkedIn验证码，平台认证"),
"en_otp_web_3216": ("TRANSACTION", "Delhivery妥投OTP+官方跟踪，物流事务"),
"en_otp_web_20581": ("TRANSACTION", "UPI注册已开始的银行安全提醒，账户业务告知"),
"en_otp_web_17115": ("TRANSACTION", "BhaiFi接入OTP，纯服务认证"),
"en_otp_web_1949": ("TRANSACTION", "bbdaily因天气延迟配送的订单服务告知"),
"en_otp_web_12722": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29783": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_29682": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_285": ("TRANSACTION", "FASTag已绑定车辆/账户的业务结果告知"),
"en_otp_web_4608": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3265": ("TRANSACTION", "ICICI借记卡交易OTP，消费确认认证"),
"en_otp_web_29595": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_6042": ("TRANSACTION", "Swiggy Instamart妥投码，物流签收事务"),
"en_otp_web_1286": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_19873": ("TRANSACTION", "IRCTC订票确认+订单OTP，票务事务"),
"en_otp_web_7823": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12424": ("TRANSACTION", "Wi-Fi接入OTP（Adopt NetTech），服务认证"),
"en_otp_web_3329": ("AD", "Lunchclub社交邀请拉新，正规服务推广非骗"),
"en_otp_web_16422": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_9808": ("TRANSACTION", "Aadhaar OTP+生物特征更新服务提醒，KYC事务"),
"en_otp_web_12459": ("TRANSACTION", "Rista登录OTP，应用认证"),
"en_otp_web_1457": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_20081": ("TRANSACTION", "OpenAI验证码，平台认证"),
"en_otp_web_8246": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16553": ("TRANSACTION", "Razorpay绑卡保存OTP，支付认证"),
"en_otp_web_1295": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_31780": ("TRANSACTION", "LoadShare配送签收OTP，物流事务"),
"en_otp_web_54964": ("TRANSACTION", "Olacabs验证码，出行服务认证"),
"en_otp_web_10569": ("TRANSACTION", "Jio防国际诈骗骚扰的运营商安全服务告知"),
"en_otp_web_4532": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_987": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_7742": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58478": ("TRANSACTION", "网约车上车OTP，出行服务事务"),
"en_otp_web_17545": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12484": ("TRANSACTION", "ClearTax手机号验证OTP，应用认证"),
"en_otp_web_33734": ("TRANSACTION", "MakeMyTrip行程预订确认+防诈提醒，订单事务"),
"en_otp_web_55461": ("AD", "BookMyShow折扣码+PayZapp返现促销，正规商家营销"),
"en_otp_web_16370": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_11627": ("AD", "Licious满减促销码拉单，正规商家广告"),
"en_otp_web_29679": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_7898": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12698": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_515": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_7852": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_303": ("TRANSACTION", "ICICI FASTag门户登录OTP，账户认证"),
"en_otp_web_4280": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29602": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_11419": ("TRANSACTION", "Kitsters登录OTP，应用认证"),
"en_otp_web_58634": ("TRANSACTION", "Ozone WiFi接入OTP，服务认证"),
"en_otp_web_27060": ("TRANSACTION", "BSE成交确认，证券交易业务结果告知"),
"en_otp_web_3463": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_1338": ("TRANSACTION", "ICICI NEFT入账成功通知，账户变动告知"),
"en_otp_web_37150": ("TRANSACTION", "Vodafone账单明细+到期应付，运营商账单事务"),
"en_otp_web_11294": ("TRANSACTION", "麦当劳订单号/电子小票，订单结果告知"),
"en_otp_web_12385": ("TRANSACTION", "AWFIS注册OTP，应用认证"),
"en_otp_web_16962": ("TRANSACTION", "LinkedIn验证码，平台认证"),
"en_otp_web_12532": ("TRANSACTION", "Openhouse登录OTP，应用认证"),
"en_otp_web_54718": ("TRANSACTION", "Flipkart交易OTP，支付认证"),
"en_otp_web_1395": ("TRANSACTION", "银行账户扣款通知，账户变动告知"),
"en_otp_web_1809": ("TRANSACTION", "Vi账单可下载的服务告知，非促销话术为主"),
"en_otp_web_4556": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_5767": ("TRANSACTION", "UTS手机票OTP，票务认证"),
"en_otp_web_9997": ("TRANSACTION", "PayU访问已存信息OTP，支付认证"),
"en_otp_web_29599": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_12687": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_67722": ("AD", "Regal Portfolio折扣码营销，含退订，正规推销非骗"),
"en_otp_web_9705": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_3036": ("TRANSACTION", "JioMart会员状态更新通知，业务结果告知"),
"en_otp_web_12727": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_59017": ("TRANSACTION", "MyWallet开户/验证OTP，账户认证"),
"en_otp_web_48162": ("FRAUD", "碎片化假中奖/领奖话术（award claim/holiday），典型诈骗"),
"en_otp_web_16974": ("TRANSACTION", "Care Health密码核验OTP，账户认证"),
"en_otp_web_57272": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_3226": ("TRANSACTION", "Tata Croma配送码给骑手，物流签收事务"),
"en_otp_web_12711": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_30536": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_1308": ("TRANSACTION", "银行账户扣款通知，账户变动告知"),
"en_otp_web_1644": ("TRANSACTION", "YES BANK外币卡消费/钱包扣款余额告知"),
"en_otp_web_56640": ("TRANSACTION", "WhatsApp验证码，平台认证"),
"en_otp_web_17395": ("TRANSACTION", "Delhivery派送中+签收OTP，物流事务"),
"en_otp_web_16178": ("TRANSACTION", "Disney+ Hotstar验证码，平台认证"),
"en_otp_web_54662": ("TRANSACTION", "用户手机号验证OTP，应用认证"),
"en_otp_web_54632": ("TRANSACTION", "WhatsApp验证码，平台认证"),
"en_otp_web_58169": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_56630": ("TRANSACTION", "WhatsApp验证码，平台认证"),
"en_otp_web_7758": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_11998": ("TRANSACTION", "BSE成交确认，证券交易业务结果告知"),
"en_otp_web_1177": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_58804": ("TRANSACTION", "SBI借记卡交易OTP，消费确认认证"),
"en_otp_web_12458": ("TRANSACTION", "Rista登录OTP，应用认证"),
"en_otp_web_210": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_3273": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3740": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3243": ("TRANSACTION", "Myntra登录OTP，应用认证"),
"en_otp_web_231": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_1223": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_3213": ("TRANSACTION", "银行账户扣款通知，账户变动告知"),
"en_otp_web_58032": ("TRANSACTION", "MyWallet开户/验证OTP，账户认证"),
"en_otp_web_32026": ("TRANSACTION", "Faber报修登记+服务密码，售后服务事务"),
"en_otp_web_4781": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58540": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_3152": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_44888": ("FRAUD", "碎片化假中奖领奖话术（claim/prize/winner），典型诈骗"),
"en_otp_web_3764": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_16404": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4374": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_9785": ("TRANSACTION", "Airtel Thanks登录OTP，应用认证"),
"en_otp_web_10640": ("TRANSACTION", "Game Theory登录OTP，应用认证"),
"en_otp_web_45294": ("FRAUD", "碎片化假账单/积分兑换话术（account statement/points/redeemed），典型诈骗"),
"en_otp_web_3052": ("TRANSACTION", "cult.fit候补课确认，预约业务结果告知"),
"en_otp_web_2955": ("TRANSACTION", "cult.fit候补课确认，预约业务结果告知"),
"en_otp_web_54967": ("TRANSACTION", "redBus OTP，出行票务认证"),
"en_otp_web_197": ("TRANSACTION", "银行卡消费通知为主；EMI提示为附带，主意图仍是账户变动"),
"en_otp_web_2601": ("TRANSACTION", "Vi半年账单可下载的服务告知"),
"en_otp_web_1290": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_3252": ("TRANSACTION", "Petpooja/Zoeys验证OTP，应用认证"),
"en_otp_web_3567": ("TRANSACTION", "Shadowfax到件签收码，物流事务"),
"en_otp_web_2958": ("TRANSACTION", "PhonePe收款请求链接，支付业务通知"),
"en_otp_web_33186": ("TRANSACTION", "Supr Delivery配送签收OTP，物流事务"),
"en_otp_web_12786": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3738": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_7868": ("TRANSACTION", "Bigbasket登录码，应用认证"),
"en_otp_web_3626": ("TRANSACTION", "BookMyForex验证OTP，应用认证"),
"en_otp_web_16448": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_161": ("TRANSACTION", "支票本寄出物流跟踪，银行业务结果告知"),
"en_otp_web_29673": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_16379": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_56363": ("AD", "Fynd Cash余额提醒+FIRST20优惠码拉单，正规促销"),
"en_otp_web_30530": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_12723": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_8957": ("TRANSACTION", "渣打银行反虚假招聘防诈提醒，银行服务告知"),
"en_otp_web_28867": ("TRANSACTION", "Jio防换卡诈骗提醒（卡纳达语），运营商安全服务告知"),
"en_otp_web_5961": ("AD", "Licious满减促销码拉单，正规商家广告"),
"en_otp_web_3270": ("TRANSACTION", "UIDAI Aadhaar OTP（所得税场景），官方KYC认证"),
"en_otp_web_9442": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_30969": ("TRANSACTION", "LoadShare配送签收OTP，物流事务"),
"en_otp_web_58536": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_20232": ("TRANSACTION", "Telegram验证码，平台认证"),
"en_otp_web_4491": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_56636": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_3589": ("TRANSACTION", "Snabbit验证OTP，应用认证"),
}
