# Hand labels for rows 401-600 (human judgment; writer only merges).
ANNOTATIONS_401_600 = {
"en_otp_web_3683": ("TRANSACTION", "政府StaySafeOnline勿泄OTP提醒，安全服务告知"),
"en_otp_web_29675": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_59043": ("TRANSACTION", "IRCTC购票交易OTP，票务支付认证"),
"en_otp_web_11576": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_4386": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58559": ("TRANSACTION", "SBI借记卡交易OTP，消费确认认证"),
"en_otp_web_12710": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_55385": ("TRANSACTION", "WhatsApp验证码，平台认证"),
"en_otp_web_7881": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58550": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_57243": ("TRANSACTION", "Snapchat验证码，平台认证"),
"en_otp_web_3342": ("TRANSACTION", "订单已发货+运单号，物流状态告知"),
"en_otp_web_1719": ("TRANSACTION", "Amex收到还款的到账告知，账户变动"),
"en_otp_web_4783": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4527": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4311": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3173": ("TRANSACTION", "Ekart今日派送+签收OTP，物流事务"),
"en_otp_web_29793": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_19481": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_456": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_4718": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1838": ("TRANSACTION", "Shriram提醒更新定存提名人，金融账户服务告知"),
"en_otp_web_1196": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_3348": ("TRANSACTION", "Link验证码，平台认证"),
"en_otp_web_9786": ("TRANSACTION", "Airtel Thanks登录OTP，应用认证"),
"en_otp_web_56111": ("TRANSACTION", "State Bank Buddy登录验号OTP，账户认证"),
"en_otp_web_58809": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_3398": ("TRANSACTION", "Ekart包裹签收OTP，物流事务"),
"en_otp_web_1298": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_17546": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_10792": ("TRANSACTION", "MakeMyTrip登录OTP，应用认证"),
"en_otp_web_4406": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_59032": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_33403": ("AD", "FreshCash到账附带套餐优惠码推销，主意图是促销拉单"),
"en_otp_web_57460": ("TRANSACTION", "手机银行OTP，账户认证"),
"en_otp_web_16377": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_7705": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_29600": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_3066": ("TRANSACTION", "Indmoney贷款EMI到期还款提醒，正规信贷账单事务"),
"en_otp_web_17594": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12405": ("TRANSACTION", "RBI勿向他人提供OTP收钱提醒，监管安全告知"),
"en_otp_web_56638": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_3411": ("TRANSACTION", "Swiggy妥投码，物流签收事务"),
"en_otp_web_4765": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4648": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_143": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_1477": ("TRANSACTION", "信用卡账单已出+到期应付，账户账单事务"),
"en_otp_web_58709": ("AD", "Foodpanda优惠码促销，正规商家广告"),
"en_otp_web_58236": ("TRANSACTION", "注册OTP，应用认证"),
"en_otp_web_58277": ("TRANSACTION", "Sulekha手机号验证码，应用认证"),
"en_otp_web_58813": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_12564": ("TRANSACTION", "Disney+ Hotstar验证码，平台认证"),
"en_otp_web_3120": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29597": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_57241": ("TRANSACTION", "Twitter Digits确认码，平台认证"),
"en_otp_web_1112": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_2978": ("TRANSACTION", "cult.fit候补课确认，预约业务结果告知"),
"en_otp_web_12756": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_7824": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1251": ("TRANSACTION", "信用卡应还总额/最低还款提醒，账单事务"),
"en_otp_web_29598": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_20235": ("TRANSACTION", "Rediffmail开户验证码，账户认证"),
"en_otp_web_4483": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57271": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_58275": ("TRANSACTION", "Sulekha手机号验证OTP，应用认证"),
"en_otp_web_57295": ("TRANSACTION", "imo验证码，平台认证"),
"en_otp_web_4399": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_2499": ("TRANSACTION", "Vi账单可下载的服务告知"),
"en_otp_web_27669": ("TRANSACTION", "渣打指引用App更新资料，银行服务告知"),
"en_otp_web_1799": ("TRANSACTION", "Vi关闭Flash消息的服务设置指引"),
"en_otp_web_19505": ("TRANSACTION", "Shadowfax妥投PIN，物流签收事务"),
"en_otp_web_3742": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16487": ("TRANSACTION", "ECI用户管理OTP，账户操作认证"),
"en_otp_web_295": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_1175": ("TRANSACTION", "信用卡还款到账通知，账户变动告知"),
"en_otp_web_4507": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58479": ("TRANSACTION", "网约车上车OTP，出行服务事务"),
"en_otp_web_10344": ("TRANSACTION", "Amex勿泄露卡密提醒，银行安全服务告知"),
"en_otp_web_57881": ("TRANSACTION", "BharatQR注册OTP，支付认证"),
"en_otp_web_16667": ("TRANSACTION", "渣打银行防假客服号码提醒，银行安全服务告知"),
"en_otp_web_58460": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_4254": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3280": ("TRANSACTION", "Acko验证OTP，保险App认证"),
"en_otp_web_38191": ("NEEDS_REVIEW", "私人闲聊回复，非目标业务短信"),
"en_otp_web_8297": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_2764": ("TRANSACTION", "Vi充值到账+账单余额告知，运营商账户事务"),
"en_otp_web_57952": ("TRANSACTION", "WhatsApp验证码，平台认证"),
"en_otp_web_3758": ("TRANSACTION", "ICICIdirect基金交易OTP，金融交易认证"),
"en_otp_web_57248": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_29680": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_12211": ("TRANSACTION", "Blowhorn今日派送+签收OTP，物流事务"),
"en_otp_web_1695": ("TRANSACTION", "Licious订单配送时间告知，订单事务"),
"en_otp_web_3403": ("TRANSACTION", "Delhivery妥投OTP，物流事务"),
"en_otp_web_1120": ("TRANSACTION", "UPI入账通知，账户变动告知"),
"en_otp_web_1943": ("TRANSACTION", "ACT宽带计划维护中断告知，运营商服务告知"),
"en_otp_web_11322": ("TRANSACTION", "Disney+ Hotstar验证码，平台认证"),
"en_otp_web_3757": ("TRANSACTION", "ICICIdirect基金交易OTP，金融交易认证"),
"en_otp_web_3401": ("TRANSACTION", "FirewallX访问OTP，服务认证"),
"en_otp_web_57252": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_8317": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17488": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16554": ("TRANSACTION", "Razorpay登录OTP，支付认证"),
"en_otp_web_57907": ("TRANSACTION", "Bigtree（BookMyShow）交易OTP，支付认证"),
"en_otp_web_12785": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1194": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_3414": ("TRANSACTION", "Meru上车OTP启动行程，出行服务事务"),
"en_otp_web_560": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_58752": ("TRANSACTION", "MobiKwik钱包交易OTP，支付认证"),
"en_otp_web_57232": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_9831": ("TRANSACTION", "Delhivery妥投OTP，物流事务"),
"en_otp_web_55468": ("TRANSACTION", "MyWallet开户/验证OTP，账户认证"),
"en_otp_web_2886": ("TRANSACTION", "Swiggy订单已送达确认，订单结果告知"),
"en_otp_web_31778": ("TRANSACTION", "LoadShare配送签收OTP，物流事务"),
"en_otp_web_57227": ("TRANSACTION", "Twitter重置密码码，账户认证"),
"en_otp_web_4721": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1367": ("TRANSACTION", "FASTag过路费扣款通知，账户变动告知"),
"en_otp_web_29579": ("TRANSACTION", "XpressBees派送确认码，物流签收事务"),
"en_otp_web_1096": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_3287": ("TRANSACTION", "Acko验证OTP，保险App认证"),
"en_otp_web_29678": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_4688": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17502": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_6228": ("TRANSACTION", "Meatigo验证OTP为主，欢迎语附带不改主意图"),
"en_otp_web_8330": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4808": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_27790": ("TRANSACTION", "渣打银行防假App更新KYC提醒，银行安全服务告知"),
"en_otp_web_16545": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3763": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_3314": ("TRANSACTION", "PolicyBazaar车险购买付款成功，订单/支付结果告知"),
"en_otp_web_4602": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17450": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29590": ("TRANSACTION", "XpressBees派送OTP，物流签收事务"),
"en_otp_web_8257": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57192": ("TRANSACTION", "Samosa登录码，应用认证"),
"en_otp_web_4641": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_9014": ("TRANSACTION", "Cult.fit验证OTP，应用认证"),
"en_otp_web_5766": ("TRANSACTION", "UTS手机票OTP，票务认证"),
"en_otp_web_17433": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4579": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58825": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_4351": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_329": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_1586": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_27791": ("TRANSACTION", "渣打银行防假运营商KYC提醒，银行安全服务告知"),
"en_otp_web_3434": ("TRANSACTION", "eNPS向PRAN缴费OTP，养老金账户认证"),
"en_otp_web_1713": ("TRANSACTION", "NPS Tier I投资市值告知，账户业务结果"),
"en_otp_web_1454": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_58769": ("TRANSACTION", "注册OTP，应用认证"),
"en_otp_web_7878": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_20101": ("TRANSACTION", "所得税e-Filing验证OTP，政务认证"),
"en_otp_web_56603": ("TRANSACTION", "Paytm登录OTP，支付认证"),
"en_otp_web_7830": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1459": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_9704": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_58624": ("TRANSACTION", "Paytm登录OTP，支付认证"),
"en_otp_web_17141": ("TRANSACTION", "BharatPe商户注册OTP，应用认证"),
"en_otp_web_108": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_1297": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_2582": ("TRANSACTION", "Vi账单已可下载，运营商账单事务"),
"en_otp_web_7809": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_3156": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_298": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_4231": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58764": ("TRANSACTION", "网约车上车OTP，出行服务事务"),
"en_otp_web_7850": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4752": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29795": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_7743": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_66598": ("FRAUD", "Vodafone假中奖领奖（award/claim code），典型诈骗"),
"en_otp_web_33783": ("TRANSACTION", "SBI Infosec勿点钓鱼链接提醒，银行安全服务告知"),
"en_otp_web_16356": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_19396": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58382": ("TRANSACTION", "Ecom Express预付件签收OTP，物流业务"),
"en_otp_web_58871": ("TRANSACTION", "Shop101手机号验证OTP，应用认证"),
"en_otp_web_57852": ("TRANSACTION", "IMS CATsApp登录OTP，应用认证"),
"en_otp_web_4570": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4379": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_9787": ("TRANSACTION", "Airtel Thanks登录OTP，应用认证"),
"en_otp_web_37485": ("TRANSACTION", "Supr Delivery配送签收OTP，物流事务"),
"en_otp_web_9046": ("TRANSACTION", "UIDAI Aadhaar OTP，官方KYC认证"),
"en_otp_web_57911": ("TRANSACTION", "NIT交易OTP，支付/业务认证"),
"en_otp_web_57228": ("TRANSACTION", "Dubsmash验证码，应用认证"),
"en_otp_web_10188": ("TRANSACTION", "Dotpe验证OTP，应用认证"),
"en_otp_web_20278": ("TRANSACTION", "Decathlon派送签收OTP，物流事务"),
"en_otp_web_59031": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_56751": ("TRANSACTION", "网约车上车OTP，出行服务事务"),
"en_otp_web_9446": ("TRANSACTION", "ICICIdirect基金交易OTP，金融交易认证"),
"en_otp_web_12761": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29594": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_55081": ("TRANSACTION", "Paytm登录OTP，支付认证"),
"en_otp_web_54729": ("TRANSACTION", "SBI设置MPIN的OTP，账户认证"),
"en_otp_web_55485": ("TRANSACTION", "SBI设置MPIN的OTP，账户认证"),
"en_otp_web_4348": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16995": ("TRANSACTION", "Delhivery妥投OTP，物流事务"),
"en_otp_web_31815": ("TRANSACTION", "Shipyaari派送中告知，物流事务"),
"en_otp_web_45661": ("FRAUD", "碎片化假中奖话术（claim/prize/winner），典型诈骗"),
"en_otp_web_4318": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4787": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_35556": ("TRANSACTION", "CAMS查看对账单链接说明，基金账户业务告知"),
"en_otp_web_19394": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
}
