# Hand labels for rows 601-800 (human judgment; writer only merges).
ANNOTATIONS_601_800 = {
"en_otp_web_4638": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_8313": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12338": ("AD", "EaseMyTrip机票酒店优惠码促销，正规商家广告"),
"en_otp_web_9067": ("TRANSACTION", "Razorpay登录OTP，支付认证"),
"en_otp_web_9464": ("TRANSACTION", "ICICIdirect基金交易OTP，金融交易认证"),
"en_otp_web_1481": ("TRANSACTION", "银行无法确认大额在线支付的账户业务告知"),
"en_otp_web_4467": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_454": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_9830": ("TRANSACTION", "Delhivery网站登录OTP，应用认证"),
"en_otp_web_27059": ("TRANSACTION", "BSE成交确认，证券交易业务结果告知"),
"en_otp_web_4431": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16747": ("TRANSACTION", "Aadhaar OTP+官方锁卡指引，KYC认证"),
"en_otp_web_3368": ("TRANSACTION", "JioHotstar验证码，平台认证"),
"en_otp_web_46016": ("FRAUD", "碎片化假账单/积分兑换话术（statement/points/redeemed），典型诈骗"),
"en_otp_web_3397": ("TRANSACTION", "Ekart今日派送+签收OTP，物流事务"),
"en_otp_web_10198": ("TRANSACTION", "Starbucks手机号验证OTP，应用认证"),
"en_otp_web_3268": ("TRANSACTION", "UIDAI Aadhaar OTP（NIC场景），官方KYC认证"),
"en_otp_web_16735": ("TRANSACTION", "麦当劳订单账单链接，订单结果告知"),
"en_otp_web_9938": ("TRANSACTION", "渣打银行访问机密资料OTP，账户认证"),
"en_otp_web_17557": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16549": ("TRANSACTION", "Razorpay登录OTP，支付认证"),
"en_otp_web_517": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_56574": ("TRANSACTION", "PhonePe操作OTP，支付认证"),
"en_otp_web_397": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_1913": ("TRANSACTION", "Amazon Food订单已送达，订单结果告知"),
"en_otp_web_3200": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_47606": ("FRAUD", "碎片化假账单/积分兑换话术（statement/points/redeemed），典型诈骗"),
"en_otp_web_7735": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_7760": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17869": ("TRANSACTION", "ICICI信用卡购买交易OTP，支付认证"),
"en_otp_web_49679": ("TRANSACTION", "网站验证码，应用认证"),
"en_otp_web_4793": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57245": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_58763": ("TRANSACTION", "网约车上车OTP，出行服务事务"),
"en_otp_web_19874": ("TRANSACTION", "IRCTC支付确认+订单OTP，票务事务"),
"en_otp_web_2554": ("TRANSACTION", "Vi欠费账单催缴，运营商账单事务"),
"en_otp_web_58474": ("TRANSACTION", "Naaptol购物OTP，应用认证"),
"en_otp_web_12057": ("TRANSACTION", "Third Wave Coffee手机号验证OTP，应用认证"),
"en_otp_web_17480": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1048": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_33987": ("TRANSACTION", "DIR-3 KYC邮箱验证OTP，政务/合规认证"),
"en_otp_web_58049": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_3347": ("TRANSACTION", "Gemini安全码，平台认证"),
"en_otp_web_17051": ("TRANSACTION", "UTI MF告知短信受DLT影响请查邮件OTP，基金服务告知"),
"en_otp_web_4354": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_55223": ("TRANSACTION", "Steam Guard码，平台认证"),
"en_otp_web_2478": ("TRANSACTION", "Vi引导在App更新邮箱/备用号，运营商账户服务告知"),
"en_otp_web_1391": ("TRANSACTION", "银行账户入账通知，账户变动告知"),
"en_otp_web_6777": ("TRANSACTION", "手机验证OTP，应用认证"),
"en_otp_web_9139": ("TRANSACTION", "Ecom Express到件+签收码，物流事务"),
"en_otp_web_1124": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_58861": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_29586": ("TRANSACTION", "XpressBees派送确认码，物流签收事务"),
"en_otp_web_1848": ("TRANSACTION", "River Platform验证码，平台认证"),
"en_otp_web_1119": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_10202": ("TRANSACTION", "Starbucks手机号验证OTP，应用认证"),
"en_otp_web_55348": ("TRANSACTION", "Steam手机确认码，平台认证"),
"en_otp_web_3759": ("TRANSACTION", "ICICIdirect基金交易OTP，金融交易认证"),
"en_otp_web_57196": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_16439": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_449": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_57250": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_10220": ("TRANSACTION", "Third Wave Coffee手机号验证OTP，应用认证"),
"en_otp_web_3138": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3041": ("TRANSACTION", "NSE交易额确认，证券业务结果告知"),
"en_otp_web_3269": ("TRANSACTION", "INDmoney登录OTP，应用认证"),
"en_otp_web_58165": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_580": ("TRANSACTION", "信用卡自动扣款到期提醒，账户业务告知"),
"en_otp_web_34875": ("TRANSACTION", "Airtel账单已支付确认，运营商账单事务"),
"en_otp_web_54708": ("TRANSACTION", "手机号验证码，应用认证"),
"en_otp_web_8318": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3427": ("TRANSACTION", "Swiggy妥投码，物流签收事务"),
"en_otp_web_350": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_32178": ("TRANSACTION", "Smartr物流签收码，物流事务"),
"en_otp_web_11594": ("AD", "Licious满减返现促销码拉单，正规商家广告"),
"en_otp_web_20563": ("TRANSACTION", "MyJio登录OTP，应用认证"),
"en_otp_web_7889": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_11578": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_1051": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_4554": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_533": ("TRANSACTION", "信用卡自动扣款到期提醒，账户业务告知"),
"en_otp_web_11211": ("TRANSACTION", "IndiGo网上值机完成+登机牌，出行事务"),
"en_otp_web_14838": ("TRANSACTION", "ICICI信用卡购买交易OTP，支付认证"),
"en_otp_web_12276": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_429": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_4485": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12755": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12420": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_32916": ("TRANSACTION", "BSE成交确认，证券交易业务结果告知"),
"en_otp_web_17566": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_9058": ("TRANSACTION", "Meatigo验证OTP为主，欢迎语附带不改主意图"),
"en_otp_web_1373": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_57193": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_55478": ("TRANSACTION", "Truecaller验证码，平台认证"),
"en_otp_web_4245": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_19455": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57268": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_9583": ("TRANSACTION", "Cult.fit验证OTP，应用认证"),
"en_otp_web_2808": ("TRANSACTION", "Vi账单明细+到期应付，运营商账单事务"),
"en_otp_web_9465": ("TRANSACTION", "ICICIdirect基金交易OTP，金融交易认证"),
"en_otp_web_58856": ("TRANSACTION", "SBI设置MPIN的OTP，账户认证"),
"en_otp_web_4343": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17448": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17516": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_34157": ("TRANSACTION", "Jio SIM配送激活码+KYC到场要求，运营商业务事务"),
"en_otp_web_4201": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_2651": ("TRANSACTION", "Vi半年账单可下载的服务告知"),
"en_otp_web_183": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_19495": ("TRANSACTION", "Blitz妥投码，物流签收事务"),
"en_otp_web_8842": ("TRANSACTION", "渣打银行防假客服号码提醒，银行安全服务告知"),
"en_otp_web_9325": ("TRANSACTION", "Delhivery妥投OTP，物流事务"),
"en_otp_web_8321": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12781": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_54627": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_17856": ("TRANSACTION", "ICICI信用卡购买交易OTP，支付认证"),
"en_otp_web_11577": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_1935": ("TRANSACTION", "Amazon验证码，平台认证"),
"en_otp_web_68115": ("FRAUD", "保证中奖£500催领（guaranteed award/claimcode），典型诈骗"),
"en_otp_web_1542": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_3637": ("TRANSACTION", "Vi App登录OTP，应用认证"),
"en_otp_web_57235": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_22584": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12469": ("TRANSACTION", "AWFIS访客注册OTP，应用认证"),
"en_otp_web_58681": ("TRANSACTION", "bewakoof登录OTP，应用认证"),
"en_otp_web_16462": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58754": ("TRANSACTION", "Netflix验证码，平台认证"),
"en_otp_web_57221": ("TRANSACTION", "Facebook确认码，平台认证"),
"en_otp_web_12283": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_10042": ("TRANSACTION", "Rista登录OTP，应用认证"),
"en_otp_web_2731": ("TRANSACTION", "Vi账单可下载的服务告知"),
"en_otp_web_58815": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_2776": ("TRANSACTION", "Vi客服工单已解决通知，运营商服务告知"),
"en_otp_web_57468": ("TRANSACTION", "TSRTC登录OTP，票务认证"),
"en_otp_web_11582": ("TRANSACTION", "Play Console验证码，平台认证"),
"en_otp_web_9463": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_55319": ("TRANSACTION", "Fynd登录码，应用认证"),
"en_otp_web_9444": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_1604": ("TRANSACTION", "银行账户入账通知，账户变动告知"),
"en_otp_web_8245": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_7763": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_5768": ("TRANSACTION", "UTS手机票OTP，票务认证"),
"en_otp_web_55090": ("TRANSACTION", "Aadhaar OTP，KYC认证"),
"en_otp_web_7727": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3322": ("AD", "Amazon Smbhav活动注册拉新，正规活动营销"),
"en_otp_web_9048": ("TRANSACTION", "UIDAI Aadhaar OTP，官方KYC认证"),
"en_otp_web_4715": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_54738": ("TRANSACTION", "Paytm登录OTP，支付认证"),
"en_otp_web_3378": ("TRANSACTION", "Ola账户密码/OTP，出行服务认证"),
"en_otp_web_1424": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_29620": ("TRANSACTION", "DTDC已送达通知，物流结果告知"),
"en_otp_web_7791": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_37971": ("TRANSACTION", "大巴票在线预订确认，出行票务事务"),
"en_otp_web_1001": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_33137": ("TRANSACTION", "IRCTC火车票PNR确认，票务事务"),
"en_otp_web_12423": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_3121": ("TRANSACTION", "ICICI信用卡交易OTP（重发），消费确认认证"),
"en_otp_web_3421": ("TRANSACTION", "Swiggy订单确认+待支付链接，订单事务"),
"en_otp_web_58031": ("TRANSACTION", "MyWallet开户/验证OTP，账户认证"),
"en_otp_web_16407": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58530": ("TRANSACTION", "快捷转账OTP，支付认证"),
"en_otp_web_38285": ("TRANSACTION", "Ola行程+上车OTP，出行服务事务"),
"en_otp_web_17504": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_19876": ("TRANSACTION", "CAMS提名人更新OTP，基金账户认证"),
"en_otp_web_1069": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_58541": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_46765": ("FRAUD", "碎片化假中奖/领奖话术（award claim），典型诈骗"),
"en_otp_web_2786": ("TRANSACTION", "Vi账单今日到期催缴，运营商账单事务"),
"en_otp_web_58628": ("TRANSACTION", "imo验证码，平台认证"),
"en_otp_web_2583": ("TRANSACTION", "Vi关闭Flash消息的服务设置指引"),
"en_otp_web_12282": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_8273": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4745": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4409": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_19499": ("TRANSACTION", "UIDAI Aadhaar OTP，官方KYC认证"),
"en_otp_web_17880": ("TRANSACTION", "BhaiFi接入OTP，纯服务认证"),
"en_otp_web_217": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_2795": ("TRANSACTION", "Vi账单日变更告知，运营商账单服务告知"),
"en_otp_web_3245": ("TRANSACTION", "Myntra提醒补邮箱/备用号以保账户安全，账户服务告知"),
"en_otp_web_3261": ("TRANSACTION", "INDmoney提现确认OTP，金融交易认证"),
"en_otp_web_16745": ("TRANSACTION", "Aadhaar OTP+官方锁卡指引，KYC认证"),
"en_otp_web_58162": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_9355": ("TRANSACTION", "Troovy登录OTP，应用认证"),
"en_otp_web_3814": ("TRANSACTION", "Act Fibernet兴趣/业务OTP，服务认证"),
"en_otp_web_55862": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_1738": ("TRANSACTION", "Vi账单到期催缴，运营商账单事务"),
"en_otp_web_9838": ("TRANSACTION", "Meatigo验证OTP为主，欢迎语附带不改主意图"),
"en_otp_web_390": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_9775": ("TRANSACTION", "Swiggy妥投码，物流签收事务"),
"en_otp_web_4565": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_10214": ("TRANSACTION", "Substack验证码，平台认证"),
"en_otp_web_31779": ("TRANSACTION", "LoadShare配送签收OTP，物流事务"),
"en_otp_web_20277": ("TRANSACTION", "Decathlon派送签收OTP，物流事务"),
"en_otp_web_112": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_42457": ("FRAUD", "碎片化假中奖话术（claim/prize/won），典型诈骗"),
"en_otp_web_9861": ("TRANSACTION", "Third Wave Coffee手机号验证OTP，应用认证"),
"en_otp_web_32114": ("TRANSACTION", "Supr Delivery配送签收OTP，物流事务"),
"en_otp_web_16385": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_7805": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3315": ("TRANSACTION", "UIDAI Aadhaar OTP（银行场景），官方KYC认证"),
"en_otp_web_3391": ("TRANSACTION", "Xoxo奖励链接访问OTP，账户/权益认证"),
}
