# Hand labels for rows 201-400 (human judgment; writer only merges).
ANNOTATIONS_201_400 = {
"en_otp_web_19865": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57255": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_4814": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12275": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_1521": ("TRANSACTION", "新增收款人后转账提醒，银行账户业务告知"),
"en_otp_web_16471": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12715": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58363": ("AD", "Foodpanda优惠码促销，正规商家广告"),
"en_otp_web_2848": ("AD", "Vi推销一键开通UPI/账单支付便利，属营销拉新"),
"en_otp_web_10206": ("TRANSACTION", "Apple ID验证码，官方账户认证"),
"en_otp_web_17656": ("TRANSACTION", "Rista登录OTP，应用认证"),
"en_otp_web_33193": ("TRANSACTION", "Supr Delivery配送签收OTP，物流事务"),
"en_otp_web_4760": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4371": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_10800": ("TRANSACTION", "MakeMyTrip登录OTP，应用认证"),
"en_otp_web_59041": ("AD", "FreeCharge充值返现优惠码，正规促销"),
"en_otp_web_201": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_17553": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58163": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_8903": ("TRANSACTION", "渣打银行防钓鱼网站提醒，银行安全服务告知"),
"en_otp_web_2974": ("TRANSACTION", "JioMart会员状态更新通知，业务结果告知"),
"en_otp_web_1326": ("TRANSACTION", "银行账户入账通知，账户变动告知"),
"en_otp_web_3664": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_57462": ("TRANSACTION", "UPI交易OTP，支付认证"),
"en_otp_web_4546": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_11581": ("TRANSACTION", "YouTube验证码，平台认证"),
"en_otp_web_4716": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3436": ("TRANSACTION", "年交易对账单OTP（Protean），账户认证"),
"en_otp_web_19785": ("TRANSACTION", "ICICIdirect退出基金提名人OTP，账户操作认证"),
"en_otp_web_1469": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_550": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_16773": ("TRANSACTION", "Cloudnine医院OTP，服务认证"),
"en_otp_web_10219": ("TRANSACTION", "Third Wave Coffee手机号验证OTP，应用认证"),
"en_otp_web_9878": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_3349": ("TRANSACTION", "Link验证码，平台认证"),
"en_otp_web_17528": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_10517": ("TRANSACTION", "勿点未知链接/勿泄OTP的反诈提醒，安全服务告知"),
"en_otp_web_55386": ("TRANSACTION", "Gaana登录码，应用认证"),
"en_otp_web_9050": ("TRANSACTION", "UIDAI Aadhaar OTP（eMudhra），官方KYC认证"),
"en_otp_web_8253": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_9863": ("TRANSACTION", "Country Delight注册OTP，应用认证"),
"en_otp_web_12523": ("TRANSACTION", "Shriram One开户核验OTP，账户认证"),
"en_otp_web_4799": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_507": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_4737": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_51156": ("AD", "Vi以漏收OTP为由推销充值套餐，属运营商营销"),
"en_otp_web_29588": ("TRANSACTION", "XpressBees派送确认码，物流签收事务"),
"en_otp_web_57469": ("TRANSACTION", "特伦甘纳运输局OTP，政务服务认证"),
"en_otp_web_552": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_3422": ("TRANSACTION", "Swiggy Instamart妥投码，物流签收事务"),
"en_otp_web_58298": ("TRANSACTION", "Abhibus验证码，票务认证"),
"en_otp_web_1595": ("TRANSACTION", "银行卡消费通知为主；EMI提示为附带，主意图仍是账户变动"),
"en_otp_web_2493": ("TRANSACTION", "骚扰短信投诉1909指引，运营商服务告知"),
"en_otp_web_2621": ("TRANSACTION", "Vi欠费账单催缴+支付入口，运营商账单事务"),
"en_otp_web_16373": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_19460": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17588": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_10191": ("TRANSACTION", "Facebook验证码，平台认证"),
"en_otp_web_53943": ("FRAUD", "博彩站首充/亏损返还奖金诱导注册充值，假奖励诈骗"),
"en_otp_web_8973": ("TRANSACTION", "渣打银行防假积分诈骗提醒，银行安全服务告知"),
"en_otp_web_4377": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4543": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_8300": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57928": ("TRANSACTION", "SBI设置MPIN的OTP，账户认证"),
"en_otp_web_2579": ("TRANSACTION", "Vi账单可下载的服务告知"),
"en_otp_web_12692": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29596": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_1273": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_4756": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4234": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1389": ("TRANSACTION", "UPI入账通知，账户变动告知"),
"en_otp_web_7771": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4446": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12285": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_3102": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4516": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4262": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_9047": ("TRANSACTION", "UIDAI Aadhaar OTP，官方KYC认证"),
"en_otp_web_58771": ("TRANSACTION", "ONN Bikes注册OTP，应用认证"),
"en_otp_web_8258": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29683": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_57273": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_8985": ("TRANSACTION", "Digi Yatra App OTP，出行服务认证"),
"en_otp_web_57229": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_17547": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17508": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_9445": ("TRANSACTION", "ICICIdirect基金交易OTP，金融交易认证"),
"en_otp_web_9734": ("NEEDS_REVIEW", "私人叙述被骗经历的闲聊，非四类业务短信"),
"en_otp_web_9320": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_2603": ("TRANSACTION", "Vi账单可下载的服务告知"),
"en_otp_web_31776": ("TRANSACTION", "LoadShare配送签收OTP，物流事务"),
"en_otp_web_57763": ("TRANSACTION", "候选人手机号验证OTP，认证事务"),
"en_otp_web_58507": ("TRANSACTION", "PhonePe操作OTP，支付认证"),
"en_otp_web_54750": ("TRANSACTION", "GATE报名手机验证OTP+报名ID，考试事务"),
"en_otp_web_4428": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_19471": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3317": ("TRANSACTION", "UIDAI Aadhaar OTP（银行场景），官方KYC认证"),
"en_otp_web_3640": ("TRANSACTION", "Vi App登录OTP，应用认证"),
"en_otp_web_4615": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_127": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_3286": ("TRANSACTION", "UIDAI Aadhaar OTP（所得税场景），官方KYC认证"),
"en_otp_web_1458": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_31080": ("TRANSACTION", "Airtel固话/宽带账单到期提醒，运营商账单事务"),
"en_otp_web_17483": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29265": ("TRANSACTION", "Decathlon派送签收OTP，物流事务"),
"en_otp_web_17591": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_32948": ("TRANSACTION", "渣打银行防COVID相关诈骗提醒，银行安全服务告知"),
"en_otp_web_506": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_16420": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_37195": ("TRANSACTION", "Supr订单配送告知+签收OTP，物流事务"),
"en_otp_web_3174": ("TRANSACTION", "Ekart包裹签收OTP，物流事务"),
"en_otp_web_58050": ("TRANSACTION", "Reliance Jio交易OTP，支付认证"),
"en_otp_web_57258": ("TRANSACTION", "ChaCha登录码，应用认证"),
"en_otp_web_20082": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_1606": ("TRANSACTION", "ICICI FASTag自动生成用户名，账户开通告知"),
"en_otp_web_1718": ("TRANSACTION", "AMEX卡消费提醒，账户变动告知"),
"en_otp_web_10212": ("TRANSACTION", "Link验证码，平台认证"),
"en_otp_web_11580": ("TRANSACTION", "Play Console验证码，平台认证"),
"en_otp_web_17226": ("TRANSACTION", "eatfit登录OTP，应用认证"),
"en_otp_web_3171": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17654": ("TRANSACTION", "Dunzo妥投OTP，物流签收事务"),
"en_otp_web_1545": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_1716": ("AD", "政府青年对话测验拉新参与（含奖），属活动推销"),
"en_otp_web_7721": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12682": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17503": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_56639": ("TRANSACTION", "PayPal安全码，平台认证"),
"en_otp_web_1314": ("TRANSACTION", "银行账户扣款通知，账户变动告知"),
"en_otp_web_2826": ("TRANSACTION", "Vi账单已出+到期应付提醒，运营商账单事务"),
"en_otp_web_8941": ("TRANSACTION", "渣打银行重置密码OTP，账户认证"),
"en_otp_web_10192": ("TRANSACTION", "Instagram验证码，平台认证"),
"en_otp_web_31905": ("TRANSACTION", "CoWIN疫苗预约确认+验证码，政务服务事务"),
"en_otp_web_26932": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3584": ("TRANSACTION", "Porter妥投确认码，物流签收事务"),
"en_otp_web_9354": ("TRANSACTION", "HealthifyMe登录OTP，应用认证"),
"en_otp_web_58817": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_57266": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_17558": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_49185": ("TRANSACTION", "MyGP PIN验证码，支付/账户认证"),
"en_otp_web_3231": ("TRANSACTION", "DigiLocker访问OTP，政务服务认证"),
"en_otp_web_17592": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17453": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4533": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3734": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_19795": ("TRANSACTION", "UIDAI Aadhaar OTP，官方KYC认证"),
"en_otp_web_9944": ("TRANSACTION", "渣打银行登录OTP，账户认证"),
"en_otp_web_16423": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_2676": ("TRANSACTION", "Vi账单逾期催缴，运营商账单事务"),
"en_otp_web_4685": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12062": ("TRANSACTION", "FatakPay手机验证OTP，应用认证"),
"en_otp_web_58637": ("TRANSACTION", "Allahabad Bank勿泄密提醒，银行安全服务告知"),
"en_otp_web_57242": ("TRANSACTION", "Steam手机号确认码，平台认证"),
"en_otp_web_36877": ("AD", "物流平台拉新开户促销（免费账户），正规商家广告"),
"en_otp_web_57461": ("TRANSACTION", "手机银行OTP，账户认证"),
"en_otp_web_9051": ("TRANSACTION", "UIDAI Aadhaar OTP，官方KYC认证"),
"en_otp_web_17479": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12280": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_3365": ("TRANSACTION", "德里机场WiFi/网络验证码，服务认证"),
"en_otp_web_32735": ("TRANSACTION", "CAMS查看对账单链接+密码说明，基金账户业务告知"),
"en_otp_web_57894": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_29664": ("TRANSACTION", "Shadowfax取件/尝试码，物流事务"),
"en_otp_web_11306": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_55330": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_12730": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_30545": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_9049": ("TRANSACTION", "Aadhaar OTP+生物特征更新提醒，KYC事务"),
"en_otp_web_58272": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_47656": ("FRAUD", "碎片化假中奖话术（claim/prize/won），典型诈骗"),
"en_otp_web_8239": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1849": ("AD", "GoDaddy取消产品挽留续费，正规商家促销"),
"en_otp_web_17599": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4820": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_32176": ("TRANSACTION", "Smartr物流签收码，物流事务"),
"en_otp_web_45316": ("FRAUD", "碎片化假账单/积分兑换话术（statement/points/redeemed），典型诈骗"),
"en_otp_web_4597": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58762": ("TRANSACTION", "网约车上车OTP，出行服务事务"),
"en_otp_web_187": ("TRANSACTION", "信用卡交易撤销入账，账户变动告知"),
"en_otp_web_19870": ("TRANSACTION", "UIDAI Aadhaar OTP，官方KYC认证"),
"en_otp_web_31855": ("TRANSACTION", "Google Pay注册已开始的安全提醒，账户业务告知"),
"en_otp_web_1589": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_19457": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3282": ("TRANSACTION", "Acko验证OTP，保险App认证"),
"en_otp_web_20293": ("TRANSACTION", "Cashify回收付款确认码，业务确认事务"),
"en_otp_web_11174": ("TRANSACTION", "axio手机号验证OTP，金融应用认证"),
"en_otp_web_3103": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_530": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_7672": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_8240": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_54698": ("TRANSACTION", "Paytm手机号验证码，账户安全认证"),
"en_otp_web_4333": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58558": ("TRANSACTION", "SBI借记卡交易OTP，消费确认认证"),
"en_otp_web_20040": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_4571": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_7897": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3202": ("TRANSACTION", "FASTag过路费扣款通知，账户变动告知"),
"en_otp_web_16438": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_182": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_10001": ("TRANSACTION", "Meatigo验证OTP为主，欢迎语附带不改主意图"),
"en_otp_web_11412": ("TRANSACTION", "Meatigo验证OTP为主，欢迎语附带不改主意图"),
"en_otp_web_12739": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
}
