# Hand labels for rows 801-1000 (human judgment; writer only merges).
ANNOTATIONS_801_1000 = {
"en_otp_web_7506": ("TRANSACTION", "Blinkit登录OTP，应用认证"),
"en_otp_web_9772": ("TRANSACTION", "Swiggy Instamart妥投码，物流签收事务"),
"en_otp_web_17652": ("TRANSACTION", "Dunzo妥投OTP，物流签收事务"),
"en_otp_web_20554": ("TRANSACTION", "Bigbasket登录码，应用认证"),
"en_otp_web_343": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_57891": ("TRANSACTION", "State Bank Anywhere激活码，账户认证"),
"en_otp_web_56587": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_12418": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_19493": ("TRANSACTION", "Blitz派送中+签收码，物流事务"),
"en_otp_web_1266": ("TRANSACTION", "银行无法确认信用卡交易的账户业务告知"),
"en_otp_web_12467": ("TRANSACTION", "Seva Sindhu OTP，政务服务认证"),
"en_otp_web_4708": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_34999": ("TRANSACTION", "Airtel账单已支付确认，运营商账单事务"),
"en_otp_web_57262": ("TRANSACTION", "RailWire上网验证码，服务接入认证"),
"en_otp_web_2968": ("TRANSACTION", "Swiggy Instamart妥投码，物流签收事务"),
"en_otp_web_1037": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_58818": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_4557": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1004": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_20283": ("TRANSACTION", "JioTV登录OTP，应用认证"),
"en_otp_web_4274": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1862": ("TRANSACTION", "Amazon Pay余额支付成功，支付结果告知"),
"en_otp_web_2727": ("TRANSACTION", "Vi账单到期催缴，运营商账单事务"),
"en_otp_web_3366": ("TRANSACTION", "德里机场网络验证码，服务认证"),
"en_otp_web_19857": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_509": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_57951": ("TRANSACTION", "WhatsApp验证码，平台认证"),
"en_otp_web_9318": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_11575": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_56403": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_20553": ("TRANSACTION", "Ola账户密码/OTP，出行服务认证"),
"en_otp_web_12056": ("TRANSACTION", "Third Wave Coffee手机号验证OTP，应用认证"),
"en_otp_web_520": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_29452": ("TRANSACTION", "Decathlon派送签收OTP，物流事务"),
"en_otp_web_1047": ("TRANSACTION", "UPI入账通知，账户变动告知"),
"en_otp_web_19182": ("TRANSACTION", "ICICI信用卡购买交易OTP，支付认证"),
"en_otp_web_17470": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29662": ("TRANSACTION", "Shadowfax取件/尝试码，物流事务"),
"en_otp_web_58472": ("TRANSACTION", "Monster.com手机验证OTP，求职平台认证"),
"en_otp_web_9072": ("TRANSACTION", "Razorpay登录OTP，支付认证"),
"en_otp_web_58159": ("TRANSACTION", "Jio Join注册OTP，运营商服务认证"),
"en_otp_web_7638": ("TRANSACTION", "Swiggy Instamart妥投码，物流签收事务"),
"en_otp_web_3380": ("TRANSACTION", "Ola账户密码/OTP，出行服务认证"),
"en_otp_web_16552": ("TRANSACTION", "Razorpay登录OTP，支付认证"),
"en_otp_web_4598": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_10234": ("TRANSACTION", "Amex勿泄露卡密提醒，银行安全服务告知"),
"en_otp_web_492": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_7836": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_10204": ("TRANSACTION", "Starbucks手机号验证OTP，应用认证"),
"en_otp_web_504": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_7820": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3267": ("TRANSACTION", "UIDAI Aadhaar OTP（所得税场景），官方KYC认证"),
"en_otp_web_2635": ("TRANSACTION", "Vi账单可下载的服务告知"),
"en_otp_web_1035": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_7794": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_2843": ("TRANSACTION", "Vi账单已出+到期应付，运营商账单事务"),
"en_otp_web_4687": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_3113": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_2840": ("TRANSACTION", "Vi账单催缴（卡纳达语），运营商账单事务"),
"en_otp_web_31919": ("TRANSACTION", "CoWIN疫苗预约确认+验证码，政务服务事务"),
"en_otp_web_32724": ("TRANSACTION", "CAMS查看对账单链接说明，基金账户业务告知"),
"en_otp_web_47774": ("FRAUD", "碎片化假中奖/领奖话术（award claim），典型诈骗"),
"en_otp_web_1703": ("TRANSACTION", "渣打银行支票当日清算规则变更告知，银行服务告知"),
"en_otp_web_1330": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_9468": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_3665": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_4594": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1445": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_36064": ("TRANSACTION", "Amex勿泄露卡密提醒，银行安全服务告知"),
"en_otp_web_1678": ("TRANSACTION", "Licious订单配送时段确认，订单事务"),
"en_otp_web_58370": ("TRANSACTION", "Dream11账户OTP，应用认证"),
"en_otp_web_2572": ("NEEDS_REVIEW", "禁毒公益宣传，非四类业务短信主意图"),
"en_otp_web_30528": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_3433": ("TRANSACTION", "Protean重置IPIN的OTP，账户认证"),
"en_otp_web_20009": ("TRANSACTION", "Purplle OTP，应用认证"),
"en_otp_web_58734": ("TRANSACTION", "Paytm登录OTP，支付认证"),
"en_otp_web_10195": ("TRANSACTION", "Instagram验证码，平台认证"),
"en_otp_web_14768": ("TRANSACTION", "ICICI信用卡购买交易OTP，支付认证"),
"en_otp_web_3305": ("TRANSACTION", "Acko报价后续服务跟进+反馈调查，业务服务告知"),
"en_otp_web_11048": ("TRANSACTION", "所得税e-Filing Add Client验证OTP，政务认证"),
"en_otp_web_48077": ("FRAUD", "碎片化假账单/积分兑换话术（statement/points/redeemed），典型诈骗"),
"en_otp_web_29601": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_57909": ("TRANSACTION", "IIM Ahmedabad交易OTP，支付/业务认证"),
"en_otp_web_2969": ("TRANSACTION", "Swiggy妥投码，物流签收事务"),
"en_otp_web_58510": ("TRANSACTION", "redBus OTP，出行票务认证"),
"en_otp_web_17459": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_234": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_3299": ("TRANSACTION", "Vi账单今日到期催缴，运营商账单事务"),
"en_otp_web_1867": ("TRANSACTION", "Amazon Pay余额充值到账，账户变动告知"),
"en_otp_web_55086": ("TRANSACTION", "Paytm登录OTP，支付认证"),
"en_otp_web_4791": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16965": ("TRANSACTION", "LinkedIn验证码，平台认证"),
"en_otp_web_57256": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_12279": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_58164": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_3104": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17422": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_9449": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_2850": ("TRANSACTION", "Vi账单已出+到期应付，运营商账单事务"),
"en_otp_web_270": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_2943": ("TRANSACTION", "bbdaily钱包余额不足可能导致无法配送的业务提醒"),
"en_otp_web_9317": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_356": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_47412": ("FRAUD", "碎片化假中奖话术（claim/prize/won），典型诈骗"),
"en_otp_web_58157": ("AD", "MyJio优惠券引导到店办Jio SIM，运营商办卡营销"),
"en_otp_web_1097": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_5765": ("TRANSACTION", "UTS手机票OTP，票务认证"),
"en_otp_web_1322": ("TRANSACTION", "银行账户出生日期已更新告知，账户业务结果"),
"en_otp_web_36053": ("TRANSACTION", "Supr Delivery配送签收OTP，物流事务"),
"en_otp_web_56369": ("TRANSACTION", "Paytm登录OTP，支付认证"),
"en_otp_web_12751": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_55861": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_3316": ("TRANSACTION", "UIDAI Aadhaar OTP（银行场景），官方KYC认证"),
"en_otp_web_45579": ("FRAUD", "碎片化假账单/积分兑换话术（statement/points/redeemed），典型诈骗"),
"en_otp_web_2658": ("TRANSACTION", "Vi账单可下载的服务告知"),
"en_otp_web_4249": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16402": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12461": ("TRANSACTION", "Rista登录OTP，应用认证"),
"en_otp_web_1599": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_12566": ("TRANSACTION", "FreeG-WiFi接入OTP，服务认证"),
"en_otp_web_9991": ("TRANSACTION", "Wi-Fi接入OTP，服务认证"),
"en_otp_web_34855": ("TRANSACTION", "Airtel固话/宽带账单到期提醒，运营商账单事务"),
"en_otp_web_1759": ("TRANSACTION", "Vi关闭Flash消息的服务设置指引"),
"en_otp_web_1427": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_19451": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1360": ("TRANSACTION", "信用卡自动扣款已成功执行，账户业务告知"),
"en_otp_web_3217": ("TRANSACTION", "HealthifyMe登录OTP，应用认证"),
"en_otp_web_55462": ("AD", "BookMyShow电影折扣码促销，正规商家广告"),
"en_otp_web_29491": ("TRANSACTION", "IRCTC火车票PNR确认，票务事务"),
"en_otp_web_16378": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_32594": ("TRANSACTION", "Shadowfax派送尝试码，物流事务"),
"en_otp_web_8286": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_12700": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4449": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_9322": ("TRANSACTION", "Delhivery信用卡实体卡派送签收OTP，物流事务"),
"en_otp_web_29266": ("TRANSACTION", "Decathlon派送签收OTP，物流事务"),
"en_otp_web_577": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_57223": ("TRANSACTION", "YouTube Go验证码，平台认证"),
"en_otp_web_17526": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_2990": ("TRANSACTION", "bbdaily配送延迟服务告知"),
"en_otp_web_1938": ("TRANSACTION", "Amazon退货取件已预约，物流事务"),
"en_otp_web_37196": ("TRANSACTION", "Supr Delivery配送签收OTP，物流事务"),
"en_otp_web_3494": ("TRANSACTION", "CoWIN疫苗预约确认+验证码，政务服务事务"),
"en_otp_web_3364": ("TRANSACTION", "德里机场网络验证码，服务认证"),
"en_otp_web_32840": ("TRANSACTION", "麦当劳订单号/电子小票，订单结果告知"),
"en_otp_web_3007": ("TRANSACTION", "Jio电子账单已发送+应付金额，运营商账单事务"),
"en_otp_web_9261": ("TRANSACTION", "Facebook验证码，平台认证"),
"en_otp_web_1637": ("TRANSACTION", "渣打银行安全开户提示，银行安全服务告知"),
"en_otp_web_57650": ("TRANSACTION", "Paytm付款卡OTP，交易认证"),
"en_otp_web_16390": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29581": ("TRANSACTION", "XpressBees派送OTP，物流签收事务"),
"en_otp_web_7711": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_1387": ("TRANSACTION", "银行账户入账通知，账户变动告知"),
"en_otp_web_7776": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_29593": ("TRANSACTION", "Gupshup企业账户登录OTP，登录认证"),
"en_otp_web_12382": ("TRANSACTION", "Apple ID验证码，官方账户认证"),
"en_otp_web_411": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_1409": ("TRANSACTION", "ACT Fibernet缴费到账确认，运营商账单事务"),
"en_otp_web_17852": ("TRANSACTION", "ICICI信用卡购买交易OTP，支付认证"),
"en_otp_web_8224": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4719": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_2498": ("TRANSACTION", "Vi账单可下载的服务告知"),
"en_otp_web_4524": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_19392": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_17605": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_349": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_9469": ("TRANSACTION", "ICICI直销账户登录OTP，认证类业务"),
"en_otp_web_17882": ("TRANSACTION", "BhaiFi接入OTP，纯服务认证"),
"en_otp_web_35437": ("TRANSACTION", "Supr Delivery配送签收OTP，物流事务"),
"en_otp_web_3464": ("TRANSACTION", "Jio OTP，运营商服务认证"),
"en_otp_web_58158": ("TRANSACTION", "Jio Join注册OTP，运营商服务认证"),
"en_otp_web_1859": ("TRANSACTION", "CERT-In/CSK防僵尸网络工具提醒，网络安全服务告知"),
"en_otp_web_1131": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_55349": ("TRANSACTION", "Steam手机确认码，平台认证"),
"en_otp_web_56572": ("TRANSACTION", "PhonePe密码重置码，账户认证"),
"en_otp_web_7753": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_58052": ("TRANSACTION", "SBI借记卡网购OTP，交易认证"),
"en_otp_web_6306": ("TRANSACTION", "Vi防冒充监管/公检法诈骗提醒，运营商安全服务告知"),
"en_otp_web_57222": ("TRANSACTION", "Google验证码，平台认证"),
"en_otp_web_4720": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_35460": ("TRANSACTION", "Capital Float申请验证码，金融应用认证"),
"en_otp_web_3122": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_5821": ("TRANSACTION", "Swiggy登录OTP，应用认证"),
"en_otp_web_1053": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_1418": ("TRANSACTION", "Amex收到还款的到账告知，账户变动"),
"en_otp_web_29807": ("TRANSACTION", "Blue Dart安全签收码，物流事务"),
"en_otp_web_17467": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57226": ("TRANSACTION", "WhatsApp验证码，平台认证"),
"en_otp_web_8222": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_57238": ("TRANSACTION", "Fynd登录码，应用认证"),
"en_otp_web_12019": ("TRANSACTION", "BSE成交确认，证券交易业务结果告知"),
"en_otp_web_1152": ("TRANSACTION", "UPI扣款通知，账户变动告知"),
"en_otp_web_1437": ("TRANSACTION", "信用卡BBPS还款到账确认，账户变动告知"),
"en_otp_web_557": ("TRANSACTION", "银行卡消费成功通知，账户变动告知"),
"en_otp_web_58471": ("TRANSACTION", "求职平台手机验证OTP，应用认证"),
"en_otp_web_16235": ("TRANSACTION", "explorex订单验证码，应用认证"),
"en_otp_web_4693": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_4341": ("TRANSACTION", "ICICI信用卡交易OTP，消费确认认证"),
"en_otp_web_16975": ("TRANSACTION", "Care Health密码核验OTP，账户认证"),
"en_otp_web_2556": ("TRANSACTION", "Vi充值到账+账单余额告知，运营商账户事务"),
}
